/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAiInferenceResultA: typeof import('./src/components/addAiInferenceResultA.vue')['default']
    AddAiInferenceResultB: typeof import('./src/components/addAiInferenceResultB.vue')['default']
    AddLot: typeof import('./src/components/AddLot.vue')['default']
    AddSN: typeof import('./src/components/AddSN.vue')['default']
    CheckLotDuplicate: typeof import('./src/components/checkLotDuplicate.vue')['default']
    CheckMongoDuplicate: typeof import('./src/components/checkMongoDuplicate.vue')['default']
    CompareResults: typeof import('./src/components/compareResults.vue')['default']
    DeleteLot: typeof import('./src/components/DeleteLot.vue')['default']
    DeleteSN: typeof import('./src/components/DeleteSN.vue')['default']
    DeleteVrsHistoryResult: typeof import('./src/components/deleteVrsHistoryResult.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    GetAiInferenceResult: typeof import('./src/components/getAiInferenceResult.vue')['default']
    GetVrsHistoryResult: typeof import('./src/components/getVrsHistoryResult.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    ProductSerialManagement: typeof import('./src/components/ProductSerialManagement.vue')['default']
    QueryLot: typeof import('./src/components/QueryLot.vue')['default']
    QuerySN: typeof import('./src/components/QuerySN.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
